### ISSUE TITLE
feature: send decoding errors to stderr

### ISSUE THREAD

**Issue by roycewilliams** [cyclone-github/hashgen#5]
For example, when doing messy base64decode work, it would be useful to send the 'Invalid Base64 string' message to stderr, so that it can be easily separated from the stdout output.

**Comment by cyclone-github** [comment]
Yes, invalid base64 strings are indeed being printed to stdout from 
https://github.com/cyclone-github/hashgen/blob/bbe9e0334063e30754fbe178a18b7624104f741e/hashgen.go#L314C1-L315C1 
instead of stderr from
https://github.com/cyclone-github/hashgen/blob/bbe9e0334063e30754fbe178a18b7624104f741e/hashgen.go#L525C1-L526C1.
